service: lifeoc-event-watch
configValidationMode: errors
frameworkVersion: "3"
useDotenv: true
plugins:
  - serverless-rust
package:
  individually: true
provider:
  name: aws
  stage: prod
  runtime: provided.al2
  region: us-east-1
  memorySize: 128
  logRetentionInDays: 7
  timeout: 300
  environment:
    OPEN_AI_KEY: ${env:OPEN_AI_KEY}
    WP_USERNAME: ${env:WP_USERNAME}
    WP_PASSWORD: ${env:WP_PASSWORD}
  apiGateway:
    apiKeys:
      - name: lifeoc
        value: ${env:AGW_API_KEY}

functions:
  watcher:
    handler: lifeoc-event-watch
    events:
      - http:
          path: /email
          method: post
          private: true

custom:
  rust:
    dockerImage: "rustserverless/lambda-rust"
    dockerTag: "nightly"
